<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="${short_description}">
    <meta name="author" content="${author}">
    <title>${meta_title}</title>

    <!-- OpenGraph -->
    <meta property="og:title" content="${meta_title}" />
    <meta property="og:type" content="website" />
    <meta property="og:description" content="${short_description}" />
	<link href="${base_url}static/css/bootstrap.min.css" rel="stylesheet" >
    <link href="${base_url}static/css/style.css" rel="stylesheet" >

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="57x57" href="${base_url}static/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="${base_url}static/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="${base_url}static/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="${base_url}static/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="${base_url}static/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="${base_url}static/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="${base_url}static/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="${base_url}static/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="${base_url}static/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="${base_url}static/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="${base_url}static/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="${base_url}static/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="${base_url}static/favicon/favicon-16x16.png">
    <link rel="manifest" href="${base_url}static/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="${base_url}static/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
</head>

<body>
	<div class="container">

        <nav class="navbar navbar-top" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex5-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="./index.html">
                    ${title}
                </a>
            </div>
            <ul class="nav navbar-nav">
                % if resource._collect_path_list and resource._collect_path_list and len(resource._collect_path_list) > 0:
                    <ul class="breadcrumb">
                    <%
                    bpath = ''
                    %>
                    % for item in resource._collect_path_list:
                        <% bpath += item %>
                        <li><a href="${base_url + resource_filename(bpath)}">${item}</a></li>
                    % endfor
                    </ul>
                % endif
            </ul>
        </nav>

        <!-- top toolbar  -->

        <div class="row">
            <div class="col-md-3">
                <ul class="list-group">
                    % for resource_name in root_resource.resources:
                        <%
                        if resource_name == '':
                            resource_name = 'index'
                        %>
                        <li class="list-group-item">
                            <a href="${base_url + resource_filename(resource_name)}">
                                ${resource_name}
                            </a>
                        </li>
                    % endfor
                </ul>
            </div>
            <div class="col-md-9">
                ${self.body()}
            </div>
            <div class="col-xs-12" id="footer">
                Generated by <a href="https://github.com/meyt/apihero">APIHero</a>
            </div>
        </div>

	</div>
    <script src="${base_url}static/js/jquery.min.js"></script>
	<script src="${base_url}static/js/bootstrap.min.js"></script>
    <script src="${base_url}static/js/script.js"></script>
</body>
</html>